# Generated by Django 4.0.5 on 2022-06-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImGoodAt',
            new_name='Skills',
        ),
    ]
