# Generated by Django 4.0.5 on 2022-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_imgoodat_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
