# Generated by Django 3.1.4 on 2022-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20220617_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='filter',
            field=models.CharField(choices=[('Core', 'Core'), ('Cechnology', 'Technology')], default='core', max_length=30),
        ),
    ]
