# Generated by Django 3.1.4 on 2022-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20220617_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='filter',
            field=models.CharField(choices=[('Core', 'Core'), ('Technology', 'Technology')], default='Core', max_length=30),
        ),
    ]
