# Generated by Django 3.1.4 on 2022-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_profile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='main_image_icons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
