# Generated by Django 3.1.4 on 2022-06-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_skills_main_image_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='text_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
