# Generated by Django 3.1.4 on 2022-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_auto_20220617_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
