# Generated by Django 3.1.4 on 2022-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_remove_profile_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='I_am_good_at_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_work_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
