# Generated by Django 3.1.4 on 2022-06-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_auto_20220617_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='I_am_good_at_text',
            new_name='contact_text',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='contact_work',
            new_name='i_am_good_at_text',
        ),
    ]
